[package]
name = "elonaire-frontend"
version = "0.1.0"
edition = "2021"
description = "My portfolio website"
readme = "README.md"
repository = "https://github.com/yewstack/yew-trunk-minimal-template"
license = "MIT OR Apache-2.0"
keywords = ["yew", "trunk"]
categories = ["gui", "wasm", "web-programming"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
log = "0.4.6"
wasm-logger = "0.2.0"
chrono = "0.4.23"
yew = { version="0.20", features=["csr"] }
yew-router = "0.17"
yew_icons = { version = "0.7.3", features = ["BootstrapFacebook", "BootstrapTwitter", "BootstrapLinkedin", "BootstrapInstagram", "BootstrapXCircle", "BootstrapHeart", "FontAwesomeRegularComments", "BootstrapShare", "BootstrapEye", "BootstrapSearch", "BootstrapHandThumbsUp"] } # crates: disable-check
cynic = "3.3.0"
web-sys = "0.3.66"
serde = "1.0.202"
