[package]
name = "techie-tenka"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.45"
gloo-net = "0.7.0"
# gql_client = "1.0.8"
gql_client = { git = "https://github.com/elonaire/gql-client-rs", branch = "quick-fixes" }
icondata = "0.7.0"
js-sys = "0.3.102"
leptos = { version = "0.8.19", features = ["csr"] }
leptos_icons = "0.7.1"
leptos_meta = "0.8.6"
leptos_router = "0.8.13"
reactive_stores = "0.4.3"
reqwest = { version = "0.13.4", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.150"
web-sys = { version = "0.3.102", features = [
    "Storage",
    "Element",
    "HtmlFormElement",
    "HtmlDivElement",
    "Window",
    "Document",
    "HtmlElement",
    "ShareData",
    "NodeList",
] }
wasm-bindgen-futures = "0.4.75"
detaxine-ui = "0.8.38"
# detaxine-ui = { git = "https://github.com/elonaire/detaxine-ui", branch = "dev" }

[profile.wasm-release]
inherits = "release"
opt-level = 'z'
lto = true
codegen-units = 1
